### ISSUE TITLE
Map.ts:14:5 Property '[Symbol.toStringTag]' has no initializer and is not definitely assigned in the constructor.

### ISSUE THREAD

**Issue by andreas-wagner** [garronej/minimal_polyfills#7]
I am a deno user and recently switched to deno's new vendoring feature.
This means I am no longer using the cached (transpiled .js) version, but rather the .ts source code.

Deno gives me the following error (minimal_polyfills@2.2.1):

```sh
TS2564 [ERROR]: Property '[Symbol.toStringTag]' has no initializer and is not definitely assigned in the constructor.
    [Symbol.toStringTag]: string;
    ~~~~~~~~~~~~~~~~~~~~
    at .../raw.githubusercontent.com/garronej/minimal_polyfills/v2.2.1/deno_dist/Map.ts:14:5
```

**Comment by andreas-wagner** [comment]
I experienced this when trying to import * as evt from "https://deno.land/x/evt@v2.3.2/mod.ts";

**Comment by andreas-wagner** [comment]
Sorry I forgot to make it reproducible, here are the steps:

```sh
mkdir _test_mp
cd _test_mp
echo "import * as evt from \"https://deno.land/x/evt@v2.3.3/mod.ts\";" > deps.ts
deno vendor --force --output=.deno_vendor deps.ts
deno run --check --import-map=.deno_vendor/import_map.json deps.ts
```

The key is to use ` --check`, so deno checks the files.

**Comment by garronej** [comment]
Thank you very much for your help
